const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript'),Module=require('module'),path=require('path');
const old=Module._load;Module._load=function(name,parent,main){if(name.startsWith('@/'))name=path.join(process.cwd(),'src',name.slice(2));return old.call(this,name,parent,main);};for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,jsx:ts.JsxEmit.ReactJSX}}).outputText,f);
const {guideReply}=require('../src/lib/ai/guideReply.ts'),{PREDEFINED_QUESTIONS}=require('../src/lib/ai/predefinedQuestions.ts');
const {reportingMonths,reportingMonthKey,reportingStart,sharePercent}=require('../src/lib/chartData.ts');
const manifest=require('../src/app/manifest.ts').default();
test('guide routes common free-text requests without an AI dependency',()=>{for(const [question,id]of [['hello','general-modules'],['how do I register an account','register'],['what is IRS','irs-overview'],['How do I request responder access?','elevate'],['How do I become a responder?','elevate'],['How can I become an admin?','elevate'],['how do I join a Mi Salud team','misalud-join'],['forgot password','password-reset'],['how to install on iPhone','install']])assert.equal(guideReply(question).matchedQuestionId,id);});
test('unmatched guide text gives usable choices and does not misread first as IRS',()=>{const reply=guideReply('first aid');assert.equal(reply.source,'clarification');assert.ok(reply.suggestions.length);assert.equal(guideReply('gibberish lorem').source,'clarification');});
test('urgent requests use the emergency reminder without diagnosis or dispatch claims',()=>{for(const text of ['I cannot breathe',"I can't breathe",'there is immediate danger','I have chest pain']){const reply=guideReply(text);assert.equal(reply.source,'emergency');assert.ok(reply.reply.includes('cannot assess symptoms or dispatch help'));}});
test('guide routes are internal and offline source matches curated content',()=>{const offline=JSON.parse(fs.readFileSync('public/pwa/guide.json'));assert.equal(offline.length,PREDEFINED_QUESTIONS.length);for(const q of PREDEFINED_QUESTIONS){if(q.href)assert.ok(q.href.startsWith('/')&&!q.href.startsWith('//'));assert.equal(offline.find(r=>r.id===q.id).answer,q.answer);}});
test('percentage comparisons use the total, not the largest category',()=>{assert.equal(sharePercent(4,10),40);assert.equal(sharePercent(6,10),60);assert.equal(sharePercent(0,0),0);});
test('calendar trends include current month and avoid end-of-month skips',()=>{const months=reportingMonths(new Date('2026-10-07T00:00:00Z'));assert.equal(months.length,12);assert.equal(months[0].month,'2025-11');assert.equal(months.at(-1).month,'2026-10');assert.equal(new Set(months.map(m=>m.month)).size,12);assert.equal(reportingMonths(new Date('2024-03-31T01:00:00Z')).at(-1).month,'2024-03');});
test('month boundaries use Asia/Manila and align query start',()=>{assert.equal(reportingMonthKey(new Date('2026-09-30T16:00:00Z')),'2026-10');assert.equal(reportingMonthKey(new Date('2026-09-30T15:59:59Z')),'2026-09');assert.equal(reportingStart(new Date('2026-10-07T00:00:00Z')).toISOString(),'2025-10-31T16:00:00.000Z');});
test('manifest has installable icons, standalone display and safe scope',()=>{assert.equal(manifest.display,'standalone');assert.equal(manifest.start_url,'/');assert.equal(manifest.scope,'/');for(const size of ['192x192','512x512'])assert.ok(manifest.icons.some(i=>i.sizes===size&&fs.existsSync('public'+i.src)));assert.ok(manifest.icons.some(i=>i.purpose==='maskable'));});
function worker(fetchImpl=async()=>new Response('network')){const events={},puts=[],deletes=[],precache=[];const cache={addAll:async urls=>precache.push(...urls),match:async()=>undefined,put:async(...args)=>puts.push(args)};const caches={open:async()=>cache,match:async()=>new Response('offline help'),keys:async()=>['harmonisys-public-old','other-app-cache'],delete:async key=>deletes.push(key)};const self={location:{origin:'https://app.example',hostname:'app.example'},clients:{claim:async()=>{}},skipWaiting:async()=>{},addEventListener:(name,handler)=>events[name]=handler};vm.runInNewContext(fs.readFileSync('public/sw.js','utf8'),{self,caches,fetch:fetchImpl,URL,Response,Promise});return{events,puts,deletes,precache};}
async function requestWorker(w,url,options={}){let promise;const request=new Request(url,options);Object.defineProperty(request,'mode',{value:options.navigation?'navigate':'cors'});w.events.fetch({request,respondWith:p=>promise=p});return promise;}
test('worker precaches only public assets and does not delete unrelated caches',async()=>{const w=worker();let promise;w.events.install({waitUntil:p=>promise=p});await promise;assert.ok(w.precache.includes('/offline.html'));assert.ok(w.precache.every(p=>!p.startsWith('/api/')&&!p.includes('uploads')));w.events.activate({waitUntil:p=>promise=p});await promise;assert.deepEqual(w.deletes,['harmonisys-public-old']);});
test('private API, writes, RSC, cross-origin and uploaded files bypass worker caching',async()=>{for(const [url,options]of [['https://app.example/api/user',{}],['https://app.example/api/irs/incidents',{method:'POST',body:'test'}],['https://app.example/dashboard?_rsc=private',{}],['https://app.example/dashboard',{headers:{RSC:'1'}}],['https://other.example/file',{}],['https://app.example/uploads/certificate.png',{}]]){const w=worker();assert.equal(await requestWorker(w,url,options),undefined);assert.equal(w.puts.length,0);}});
test('offline protected navigation returns public help rather than stored account pages',async()=>{const w=worker(async()=>{throw new Error('offline')});const result=await requestWorker(w,'https://app.example/dashboard',{navigation:true});assert.equal(await result.text(),'offline help');assert.equal(w.puts.length,0);});
test('online authenticated navigation is never cached',async()=>{const w=worker(async()=>new Response('private user page',{headers:{'Cache-Control':'private, no-store'}}));const result=await requestWorker(w,'https://app.example/dashboard',{navigation:true});assert.equal(await result.text(),'private user page');assert.equal(w.puts.length,0);});
test('public static responses marked private or no-store are not cached',async()=>{const w=worker(async()=>new Response('private',{headers:{'Cache-Control':'private, no-store'}}));await requestWorker(w,'https://app.example/_next/static/chunks/test.js');assert.equal(w.puts.length,0);});

test('interactive charts avoid server/client SVG hydration mismatches while retaining data tables',()=>{const React=require('react'),{renderToString}=require('react-dom/server');const {ActivityTrend}=require('../src/components/charts/ReadableCharts.tsx');const html=renderToString(React.createElement(ActivityTrend,{rows:[{label:'Oct 2026',reports:3}],series:[{key:'reports',label:'Reports'}]}));assert.ok(html.includes('Preparing chart'));assert.ok(html.includes('Oct 2026'));assert.ok(!html.includes('recharts-surface'));});
test('unavailable assessment data does not return a misleading zero summary',async()=>{const exports={};const source=ts.transpileModule(fs.readFileSync('src/lib/action/unahon.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const mocks={'@/lib/prisma':{prisma:{unahon:{findMany:async()=>{throw new Error('Test database unavailable')}}}},'@/lib/access':{requireUser:async()=>({id:'synthetic',role:'ADMIN'})},'@/lib/validation':require('../src/lib/validation.ts'),'@/constants/Unahon':require('../src/constants/Unahon.ts'),'@prisma/client':require('@prisma/client'),'next/cache':{revalidatePath(){}}};vm.runInNewContext(source,{exports,console,require:name=>mocks[name]});await assert.rejects(exports.getUnahonFormsSummary(),/could not be loaded/);});
